name = "my-portfolio-remix"
type = "javascript"

zone_id = ""
account_id = ""
route = ""
workers_dev = true

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run miniflare:prod"
watch_dir = "build/index.js"

[build.upload]
format="service-worker"
